name = "MCMphotolysis"
uuid = "37f95c2c-7f9b-11e8-13ad-816be0d1e117"
authors = ["Peter Bräuer <pb866@york.ac.uk>"]
julia = "≥0.7"
version = "0.2.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
filehandling = "4b8ed5e0-8069-11e8-094b-3f5425e6acdd"
pyp = "1f59166c-d923-11e8-01b9-e713fdda0351"
